version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
  database:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  db_data:
