version: '3.4'

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
    command: /bin/sh -c "./entrypoints/docker-entrypoint.sh"
  database:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
